PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bibo:     <http://purl.org/ontology/bibo/>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>
PREFIX tib:      <http://vivo.mydomain.edu/ontology/tib-local#>
PREFIX vcard:    <http://www.w3.org/2006/vcard/ns#>
PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>
PREFIX vivo:     <http://vivoweb.org/ontology/core#>

SELECT (?keyword_id AS ?id) (?keyword_id AS ?uri) (?bezeichnung AS ?title) (GROUP_CONCAT(DISTINCT ?document_id; separator="; ") AS ?publications) (GROUP_CONCAT(DISTINCT ?project_id; separator="; ") AS ?projects) (COUNT(DISTINCT ?document_id) AS ?count)
WHERE
{
  OPTIONAL{
    ?document_id a bibo:Document .
    ?document_id vivo:hasSubjectArea ?keyword_id .
  }
  ?keyword_id rdfs:label ?bezeichnung .
    FILTER (regex(?bezeichnung, "(Concept)") != true ) .
  OPTIONAL {
    ?project_id a vivo:Grant .
    ?author_id vivo:relatedBy ?project_id .
  }
}
GROUP BY ?keyword_id ?bezeichnung
ORDER BY ?bezeichnung