PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vitro:    <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX bibo:     <http://purl.org/ontology/bibo/>
PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX vcard:    <http://www.w3.org/2006/vcard/ns#>
PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>
PREFIX vivo:     <http://vivoweb.org/ontology/core#>


SELECT DISTINCT (?grant_id AS ?id) ?title (?grant_id AS ?uri) (GROUP_CONCAT(DISTINCT ?document_id; separator="; ") AS ?publications) (COUNT(DISTINCT ?document_id) AS ?count) (GROUP_CONCAT(DISTINCT ?keyword; separator="; ") AS ?keywords) (GROUP_CONCAT(DISTINCT ?inv_id; separator="; ")AS ?investigators) ?start ?end ?abstract ?principal_investigator
WHERE
{
  ?grant_id a vivo:Grant .
  ?grant_id rdfs:label ?title .
  OPTIONAL { ?grant_id bibo:abstract ?abstract }
  OPTIONAL {
    ?document_id a bibo:Document .
    ?grant_id vivo:supportedInformationResource ?document_id .
  }
  OPTIONAL { ?grant_id vivo:hasSubjectArea ?keyword }
  ?grant_id vivo:dateTimeInterval ?dateInterval .
  ?dateInterval vivo:start ?startInd .
  ?dateInterval vivo:end ?endInd .
  ?startInd vivo:dateTime ?start .
  ?endInd vivo:dateTime ?end .
  OPTIONAL{
    ?principal_investigator a vivo:PrincipalInvestigatorRole .
    ?grant_id  vivo:relatedBy ?principal_investigator . 
  }
  OPTIONAL { 
    ?inv_id a foaf:Person .
    ?inv_id vivo:relatedBy ?grant_id .
  }
}
GROUP BY ?grant_id ?title ?abstract ?start ?end ?principal_investigator
ORDER BY ?title