#!/bin/sh

cd ~/src/jena-fuseki-1.1.1-vivo/

./s-query --service http://localhost:2020/ds/query 'PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#> PREFIX bibo:     <http://purl.org/ontology/bibo/> PREFIX skos:     <http://www.w3.org/2004/02/skos/core#> PREFIX tib:      <http://vivo.mydomain.edu/ontology/tib-local#> PREFIX vcard:    <http://www.w3.org/2006/vcard/ns#> PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#> PREFIX vivo:     <http://vivoweb.org/ontology/core#> SELECT (?keyword_id AS ?id) (?keyword_id AS ?uri) (?bezeichnung AS ?title) (GROUP_CONCAT(DISTINCT ?document_id; separator="; ") AS ?publications) (GROUP_CONCAT(DISTINCT ?project_id; separator="; ") AS ?projects) (COUNT(DISTINCT ?document_id) AS ?count) WHERE { OPTIONAL{ ?document_id a bibo:Document . ?document_id vivo:hasSubjectArea ?keyword_id .} ?keyword_id rdfs:label ?bezeichnung . FILTER (regex(?bezeichnung, "(Concept)") != true ) . OPTIONAL { ?project_id a vivo:Grant . ?author_id vivo:relatedBy ?project_id . } } GROUP BY ?keyword_id ?bezeichnung ORDER BY ?bezeichnung' > ~/tomcat/webapps/vivo-test/vivopaths/data/spql_keywords.json

./s-query --service http://localhost:2020/ds/query 'PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#> PREFIX vitro:    <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#> PREFIX bibo:     <http://purl.org/ontology/bibo/> PREFIX foaf:     <http://xmlns.com/foaf/0.1/> PREFIX vcard:    <http://www.w3.org/2006/vcard/ns#> PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#> PREFIX vivo:     <http://vivoweb.org/ontology/core#> SELECT (?author_id AS ?id) (?name AS ?fullname) (?author_id AS ?uri) (GROUP_CONCAT(DISTINCT ?gnd_id; separator="; ") AS ?gnd) (?bytestreamUri AS ?image) (GROUP_CONCAT(DISTINCT ?org_label; separator="; ") AS ?positions) ?name (COUNT(DISTINCT ?document_id) AS ?count) (GROUP_CONCAT(DISTINCT ?project_id; separator="; ") AS ?projects) (GROUP_CONCAT(DISTINCT ?document_id; separator="; ") AS ?publications) WHERE { ?author_id a foaf:Person . ?author_id rdfs:label ?name .OPTIONAL { ?author_id vitro-public:mainImage ?picture . ?picture vitro-public:downloadLocation ?bytestreamUri . } OPTIONAL { ?pos a vivo:Position . ?author_id vivo:relatedBy ?pos . ?org a foaf:Organization . ?pos vivo:relates ?org . ?org rdfs:label ?org_label . } ?authorship_id a vivo:Authorship . ?authorship_id vivo:relates ?author_id . ?document_id a bibo:Document . ?document_id vivo:relatedBy ?authorship_id . OPTIONAL { ?project_id a vivo:Grant . ?author_id vivo:relatedBy ?project_id . } } GROUP BY ?author_id ?bytestreamUri ?name ORDER BY ?name' > ~/tomcat/webapps/vivo-test/vivopaths/data/spql_authors.json

./s-query --service http://localhost:2020/ds/query 'PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#> PREFIX vitro:    <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#> PREFIX bibo:     <http://purl.org/ontology/bibo/> PREFIX foaf:     <http://xmlns.com/foaf/0.1/> PREFIX vcard:    <http://www.w3.org/2006/vcard/ns#> PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#> PREFIX vivo:     <http://vivoweb.org/ontology/core#> SELECT DISTINCT (?document_id AS ?id) ?title (?document_id AS ?uri) (GROUP_CONCAT(DISTINCT ?person_id; separator="; ") AS ?authors) (GROUP_CONCAT(DISTINCT ?project_id; separator="; ") AS ?projects) ?abstract (GROUP_CONCAT(DISTINCT ?keyword; separator="; ") AS ?keywords) ?year WHERE { ?document_id a bibo:Document . ?document_id rdfs:label ?title . ?authorship_id a vivo:Authorship . ?authorship_id vivo:relates ?document_id . ?person_id a foaf:Person . ?authorship_id vivo:relates ?person_id. ?person_id rdfs:label ?name . OPTIONAL { ?document_id bibo:abstract ?abstract } OPTIONAL { ?document_id vivo:hasSubjectArea ?keyword } OPTIONAL { ?document_id vivo:dateTimeValue ?year } OPTIONAL { ?project_id a vivo:Grant . ?document_id vivo:informationResourceSupportedBy ?project_id. }} GROUP BY ?document_id ?title ?abstract ?year ORDER BY ?title' >  ~/tomcat/webapps/vivo-test/vivopaths/data/spql_pubs.json

./s-query --service http://localhost:2020/ds/query 'PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#> PREFIX vitro:    <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#> PREFIX bibo:     <http://purl.org/ontology/bibo/> PREFIX foaf:     <http://xmlns.com/foaf/0.1/> PREFIX vcard:    <http://www.w3.org/2006/vcard/ns#> PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#> PREFIX vivo:     <http://vivoweb.org/ontology/core#> SELECT DISTINCT (?grant_id AS ?id) ?title (?grant_id AS ?uri) (GROUP_CONCAT(DISTINCT ?document_id; separator="; ") AS ?publications) (COUNT(DISTINCT ?document_id) AS ?count) (GROUP_CONCAT(DISTINCT ?keyword; separator="; ") AS ?keywords) (GROUP_CONCAT(DISTINCT ?inv_id; separator="; ")AS ?investigators) ?start ?end ?abstract ?principal_investigator WHERE { ?grant_id a vivo:Grant . ?grant_id rdfs:label ?title . OPTIONAL { ?grant_id bibo:abstract ?abstract } OPTIONAL { ?document_id a bibo:Document . ?grant_id vivo:supportedInformationResource ?document_id . } OPTIONAL { ?grant_id vivo:hasSubjectArea ?keyword } ?grant_id vivo:dateTimeInterval ?dateInterval . ?dateInterval vivo:start ?startInd . ?dateInterval vivo:end ?endInd . ?startInd vivo:dateTime ?start . ?endInd vivo:dateTime ?end . OPTIONAL{ ?principal_investigator a vivo:PrincipalInvestigatorRole . ?grant_id  vivo:relatedBy ?principal_investigator .  } OPTIONAL { ?inv_id a foaf:Person . ?inv_id vivo:relatedBy ?grant_id . }} GROUP BY ?grant_id ?title ?abstract ?start ?end ?principal_investigator ORDER BY ?title' > ~/tomcat/webapps/vivo-test/vivopaths/data/spql_projects.json

perl ~/tomcat/webapps/vivo-test/vivopaths/data/merge.pl